### ISSUE TITLE
Single instance of Onboard in Provider

### ISSUE THREAD

**Issue by hammadj** [talentlessguy/use-onboard#4]
Wondering if there's any plans on moving the core logic to a Provider so that you can use useOnboard in multiple places in the app without instantiating it multiple times. Also, would it be possible to use this alongside https://usedapp.readthedocs.io/ ?

**Comment by talentlessguy** [comment]
1. yes you can do that already

```tsx
import { createContext } from 'react'
import { useOnboard } from 'use-onboard'

const Ctx  = createContext()

const App = () => {
  const instance = useOnboard(...)

  return <Ctx value={instance}><Component /></Ctx>
}
```

and then inside the `Cmponent` use `useContext(Ctx)`

2. I might be wrong but doesn't useDapp include wallet onboarding already? Judging by https://usedapp.readthedocs.io/en/latest/getting-started.html#example
